[package]
name = "chat"
version = "1.0.0"
authors = []

[addresses]
chat_addr = "8c9e3104a866a70ebee3d3aab02ff66d5d7a70993f0f04899f5424d47bf1d10a"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
std = "0x1"

[dev-dependencies]
